version: '3'
services:
  mariadb:
    user: root
    image: 'bitnami/mariadb:latest'
    container_name: moodle-db
    environment:
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=p@$$w0rd
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=m00dl3
      - MARIADB_DATABASE=bitnami_moodle
    volumes:
      - '$PWD/mariadb_data:/bitnami'
    networks:
      - net
  moodle:
    image: 'bitnami/moodle:latest'
    container_name: moodle-web
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=m00dl3
      - MOODLE_DATABASE_NAME=bitnami_moodle
    ports:
      - '80:80'
      - '443:443'
    expose: ["80"]
    volumes:
      - '$PWD/moodle_data:/bitnami'
    depends_on:
      - mariadb
    networks:
      - net
networks:
  net: