version: '3'
services:
  apache2:
    image: httpd:latest
    container_name: owen-apache2
    ports:
      - 8081:80
    volumes: 
      - $PWD/htdocs:/usr/local/apache2/htdocs/
    networks:
      - net
networks:
  net: