version: '3'
services:
  nginx-web1:
    image: nginx:latest
    container_name: nginx-web1
    ports:
      - 8081:80
    volumes: 
      - $PWD/web1/content:/usr/share/nginx/html:ro
    networks:
      - net
  nginx-web2:
    image: nginx:latest
    container_name: nginx-web2
    ports:
      - 8082:80
    volumes: 
      - $PWD/web2/content:/usr/share/nginx/html:ro
    networks:
      - net
  nginx-web3:
    image: nginx:latest
    container_name: nginx-web3
    ports:
      - 8083:80
    volumes: 
      - $PWD/web3/content:/usr/share/nginx/html:ro
    networks:
      - net
  nginx-lb:
    image: nginx:stable
    container_name: nginx-lb
    ports:
      - 80:80
    expose:
      - 80
    volumes: 
      - $PWD/nginx_confd/lb.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net    
networks:
  net:      

