version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
        - ./code:/code
        - ./site.conf:/etc/nginx/conf.d/site.conf
    networks:
      - net
    links:
      - php
  php:
    container_name: php
    image: php:7-fpm
    volumes:
        - ./code:/code
    networks:
      - net      
networks:
  net: 

